name: Solar Energy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2658125776797533
title: 'EWS TECH HK Solar Panels, Systems, The Best.. For Less!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d1deef'
    - '#637484'
    - '#25242a'
    - '#246930'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
